# Generated by Django 3.1.4 on 2021-05-01 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='fav_index',
            field=models.CharField(default='^IBEX', max_length=20),
        ),
    ]
