version: "3.8"
   
services:
  db:
    image: mysql:8.0.24
    container_name: investapp_db
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    ports:
      - "3306:3306"
    expose:
      - "3306"
    networks:
      - invest-system
  web:
    build: .
    entrypoint: ./entrypoint.sh
    volumes:
      - .:/investApp
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_started
    networks:
      - invest-system

networks:
  invest-system:
    external: true
